Deployment fix
VaporFi/liquid-mining pull request #40
Opened 2023-06-15 11:51 UTC by parth-15

fixes due to bug in deployment that was missed in earlier code reviews

2023-06-15 12:20 UTC, mejiasd3v approved these changes

2023-06-15 15:56 UTC, Thehitesh172 approved these changes

2023-06-15 15:57 UTC, Thehitesh172 commented
Looks good, but package-lock.json

2023-06-16 07:31 UTC, mejiasd3v requested changes
remove package-lock.json, use yarn

2023-06-16 08:01 UTC, merged